resources:
  - name: proctor-source
    type: git
    source:
      uri: git://github.com/rosenhouse/proctor
      branch: master

jobs:
  - name: test
    plan:
      - get: proctor-source
        trigger: true
      - task: test
        file: proctor/ci/test.yml
