resources:
  - name: proctor-source
    type: git
    source:
      uri: git://github.com/rosenhouse/proctor
      branch: master

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:rosenhouse/proctor
      branch: version
      file: version
      private_key: {{ci_bot_github_ssh_key}}

  - name: github-release
    type: github-release
    source:
      user: rosenhouse
      repository: proctor
      access_token: {{ci_bot_github_token}}
      drafts: true

jobs:
  - name: test
    plan:
      - get: proctor-source
        trigger: true
      - task: test
        file: proctor-source/ci/test.yml

  - name: shipit
    plan:
      - aggregate:
        - get: proctor-source
          passed: [test]
        - get: version
          params: {bump: minor}
      - task: prep-release
        file: proctor-source/ci/prep-release.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/name
          commitish: release-notes/commitish
          globs:
            - binaries/*
      - put: version
        params: { file: version/number }
